scout:
  # Publish all joint states -----------------------------------
  /scout/joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Position Controllers ---------------------------------------
  /scout/joint1_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint1
    pid: {p: 0.05, i: 0.0001, d: 0.05}
  /scout/joint2_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint2
    pid: {p: 0.05, i: 0.0001, d: 0.05}
  /scout/joint3_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint3
    pid: {p: 0.05, i: 0.0001, d: 0.05}
  /scout/joint4_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint4
    pid: {p: 0.05, i: 0.0001, d: 0.05}
